### ISSUE TITLE
Integration with NeoComplCache.

### ISSUE THREAD

**Issue by naquad** [xolox/vim-lua-ftplugin#11]
Please help! https://github.com/Shougo/neocomplcache/issues/401

**Comment by xolox** [comment]
Hi Daniel! Based on my reading of issue Shougo/neocomplcache#401 you're asking me to merge pull request #10. You could have made that a little more explicit :-). Anyway I'll check out your pull request!

**Comment by xolox** [comment]
I'm closing this issue now because I merged your pull request, so the plug-in should now work properly.
