### ISSUE TITLE
Do not map ", ', .

### ISSUE THREAD

**Issue by naquad** [xolox/vim-lua-ftplugin#13]
If one has other plugins mapping " and ' (like delimitmate) then they'll be overriden and thats inconvinience. Please add at least an option to disable those mappings. Thanks.

**Comment by xolox** [comment]
Sure, will do.

**Comment by xolox** [comment]
Thanks for the suggestion Daniel, I've just added the option [lua_define_completion_mappings](https://peterodding.com/code/vim/lua-ftplugin#lua_define_completion_mappings_option). If you set it to 0 the mappings will no longer be defined.
