### ISSUE TITLE
The % mapping cycles between the relevant keywords doesn't work!

### ISSUE THREAD

**Issue by jblereste** [xolox/vim-lua-ftplugin#18]
Hi!

As you can see in the title of this post, when I press the key "%" on a lua revelant keywords nothing happens!
Do you have any ideas?

My config
$ vim --version
VIM - Vi IMproved 7.4 
Included patches: 1-52

lua-ftplugin : 0.7.12

Anyway, thank you for this plugin :)

Jb

**Comment by LakeByTheWoods** [comment]
In the same boat :P

**Comment by xolox** [comment]
Do you guys have the [matchit](http://vimdoc.sourceforge.net/htmldoc/usr_05.html#matchit-install) plug-in installed? I suppose not :-). It's mentioned in the documentation.

**Comment by xolox** [comment]
I'm going to go ahead and close this issue now. If the problem persists please feel free to reopen this issue or create a new one. Thanks for the feedback and happy Vimming!

**Comment by flamendless** [comment]
Im going to reopen this issue.
I have matchit plugin from here https://github.com/adelarsq/vim-matchit

The % works, but if
`lua
function()
  if something then

 end
end
`
If i'm in the word `function`, it jumps to the `end` pair of the `if`
