### ISSUE TITLE
Feature request: add support for shell.vim

### ISSUE THREAD

**Issue by solohan** [xolox/vim-lua-ftplugin#2]
Hi,

Would it be possible to add support for the shell.vim (http://www.vim.org/scripts/script.php?script_id=3123) plugin you wrote, as you have done for the LuaInspect (http://www.vim.org/scripts/script.php?script_id=3169) plugin? This would eliminate a command prompt window popup everytime "luac" is invoked on a Windows machine.

**Comment by xolox** [comment]
Hi solohan,

Yes the console window is definitely annoying. I don't use Windows much anymore so never noticed the issue, however I've just updated the plug-in. It should now automatically use the shell.vim plug-in when you have both of the plug-ins installed. Can you confirm whether it works for you? If it does then feel free to close this issue.

Thanks for the feedback and happy Vimming!

 - Peter

**Comment by solohan** [comment]
Hi Peter,

Thanks for the fix! Works perfectly!

SoloHan.
