### ISSUE TITLE
possible to include custom .lua and .pkg file in omnifunc?

### ISSUE THREAD

**Issue by yi** [xolox/vim-lua-ftplugin#24]
Hi Peter Odding,

Many thanks for the vim-lua-ftplugin. I have been using it in my diary job, it saves me a lot of time indeed. 

Now we starting working on a project heavily based on an existing c++ lua framework. I'm wondering is it possible to add the [lua files](https://github.com/yi/quick-cocos2d-x/tree/develop/framework) and [pkg files](https://github.com/yi/cocos2d-x/tree/v2x/tools/tolua%2B%2B) to omnifunc? So we can have the nice auto completion. 

Sadly I'm not familair with the vim script language. I have tried a couple attempts, but no luck. 

Could you give me some hint. 

Thank you.

**Comment by stormc** [comment]
Do you have $LUA_PATH set to include the directory of your lua files?

**Comment by xolox** [comment]
I was wondering the same thing as @stormc, basically it should magically work assuming proper coding practices and an environment that allows vim-lua-ftplugin to introspect everything / most modules.

**Comment by yi** [comment]
Thanks @xolox and @stormc, $LUA_PATH works indeed. It was my fault. I forgot add `?.lua` in the LUA_PATH
