### ISSUE TITLE
Omnifunc issue

### ISSUE THREAD

**Issue by chrsm** [xolox/vim-lua-ftplugin#25]
Hi, thanks for the awesome plugin. I ran into a small issue tonight, and I'm not sure how to approach it. Whenever I press '.', omnifunc is triggered and throws the following error:

Error detected while processing function xolox#lua#omnifunc:
E712: Argument of filter() must be a List or Dictionary

Any tips on what I've done wrong? This is a basic install with the exception of using (or trying to use) let g:lua_complete_omni = 1.

**Comment by xolox** [comment]
Can you try again with the latest version? I may have just solved this issue and a couple of other previously reported issues, see 4746f4d4bddb51619c2956d73adfb22b73e066dd for details (if you're curious).

**Comment by chrsm** [comment]
Woops. Updating to latest causes vim to segfault.

```
Vim: Caught deadly signal TRAP
Vim: preserving files...
Vim: Finished.
[1] 19935 trace trap (core dumped) vim test.lua
```

**Comment by actionless** [comment]
when i trying to complete any lua code i receiving an error:

``` lua
Error detected while processing function xolox#lua#omnifunc..xolox#lua#getomnivariables..xolox#lua#dofile:
line    4:
E121: Undefined variable: output
Press ENTER or type command to continue
Error detected while processing function xolox#lua#omnifunc..xolox#lua#getomnivariables..xolox#lua#dofile:
line   31:
...ndle/vim-lua-ftplugin/misc/lua-ftplugin/omnicomplete.lua:85: variable 'ldoc.builtin.io' is not declared
Press ENTER or type command to continue
Error detected while processing function xolox#lua#omnifunc..xolox#lua#getomnivariables:
line    3:
E121: Undefined variable: Error
```

**Comment by xolox** [comment]
@chrsm: For now you can add `let g:lua_internal = 0` to your vimrc to at least stop Vim from crashing; with this setting an external Lua interpreter will be used, so if that crashes it won't take down Vim. You can also try the [lua_omni_blacklist](http://peterodding.com/code/vim/lua-ftplugin#lua_omni_blacklist_option) option (the documentation contains an example which might be relevant for you).

**Comment by chrsm** [comment]
I will try that this weekend and see what happens. Thank you, xolox!

**Comment by chrsm** [comment]
Just tried it right now, `let g:lua_internal = 0` does the trick.
