### ISSUE TITLE
Quickfix opens luac binary

### ISSUE THREAD

**Issue by actionless** [xolox/vim-lua-ftplugin#26]
Steps to reproduce:
1) `let g:lua_compiler_name = '/usr/sbin/luac5.1'`
2) `touch test.lua; vim test.lua`
3) write smth like `abc=123`
4) `:LuaCheckGlobals`
5) press [Enter]

expected result:
jump to `test.lua:1`

actual result:
`/usr/sbin/luac5.1` binary loaded into the new buffer

**Comment by hewei-chn** [comment]
see pull #38 , I think it will works for you .

**Comment by actionless** [comment]
@hewei-chn thanks, but i have already moved to https://github.com/scrooloose/syntastic/wiki/Syntax-Checkers which is more generalized solution and support `luac` and/or `luacheck`
