### ISSUE TITLE
Omni completion not compatible with strict.lua

### ISSUE THREAD

**Issue by xolox** [xolox/vim-lua-ftplugin#27]
In issue #25 @actionless reported the following:

> when i trying to complete any lua code i receiving an error:
> 
> ``` lua
> Error detected while processing function xolox#lua#omnifunc..xolox#lua#getomnivariables..xolox#lua#dofile:
> line    4:
> E121: Undefined variable: output
> Press ENTER or type command to continue
> Error detected while processing function xolox#lua#omnifunc..xolox#lua#getomnivariables..xolox#lua#dofile:
> line   31:
> ...ndle/vim-lua-ftplugin/misc/lua-ftplugin/omnicomplete.lua:85: variable 'ldoc.builtin.io' is not declared
> Press ENTER or type command to continue
> Error detected while processing function xolox#lua#omnifunc..xolox#lua#getomnivariables:
> line    3:
> E121: Undefined variable: Error
> ```

Although I've never personally used `strict.lua` I am familiar with it so I recognized the error message "variable '...' is not declared". This should be pretty easy to fix.

**Comment by xolox** [comment]
@actionless: Can you confirm whether this is fixed in the latest version?

**Comment by actionless** [comment]
@xolox, it is, thanks for the quick fix

**Comment by xolox** [comment]
Okay, good to hear. Thanks for the bug report and confirmation. I'll go ahead and close this issue now. Happy Vimming!
