### ISSUE TITLE
luafile lua_omni.lua path for VAM.

### ISSUE THREAD

**Issue by stardiviner** [xolox/vim-lua-ftplugin#5]
I'm using vim-addon-manager, when I install your plugin from VAM, it happens this error:

```
Error detected while processing /home/chris/Git/dotfiles/.vim/vim-addons/lua_omni/ftplugin/lua_
omni.vim:                                                                                      
line   29:                                                                                     
cannot open /home/chris/.vim/ftplugin/lua_omni.lua: No such file or directory
```

I checked out source code, find `luafile ~/.vim/ftplugin/lua_omni.lua`, maybe here should use more smart path settings.

**Comment by xolox** [comment]
Hi & thanks for the feedback. I'm pretty sure this has since been fixed. Please try the latest version. I'm closing this issue now but if the problem persists feel free to reopen this issue or create a new one.
